"""empty message

Revision ID: 215392b11b0e
Revises: 824268a7a675
Create Date: 2019-03-20 17:11:43.674304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '215392b11b0e'
down_revision = '824268a7a675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.create_index('textsearch_idx', 'project_info', ['text_searchable'], unique=False)
    op.add_column('projects', sa.Column('map_editors', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('projects', sa.Column('validate_editors', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_projects_map_editors'), 'projects', ['map_editors'], unique=False)
    op.create_index(op.f('ix_projects_validate_editors'), 'projects', ['validate_editors'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_validate_editors'), table_name='projects')
    op.drop_index(op.f('ix_projects_map_editors'), table_name='projects')
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('projects', 'validate_editors')
    op.drop_column('projects', 'map_editors')
    op.drop_index('textsearch_idx', table_name='project_info')
    op.drop_index('idx_project_info composite', table_name='project_info')
    # ### end Alembic commands ###
